# configuration for https://github.com/probot/autolabeler

documentation: ["/docs", "/doc-examples"]
dependency-change: "/project/Dependencies.scala"

'p:amqp': ["/amqp"]
'p:avroparquet': ["/avroparquet"]
'p:aws-event-bridge': ["/aws-event-bridge"]
'p:aws-lambda': ["/awslambda"]
'p:aws-s3': ["/s3"]
'p:aws-sns': ["/sns"]
'p:aws-sqs': ["/sqs"]
'p:azure-storage-queue': ["/azure-storage-queue"]
'p:cassandra': ["/cassandra"]
'p:csv': ["/csv", "/csv-bench"]
'p:couchbase': ["/couchbase"]
'p:dynamodb': ["/dynamodb"]
'p:elasticsearch': ["/elasticsearch"]
'p:file': ["/file"]
'p:ftp': ["/ftp"]
'p:geode': ["/geode"]
'p:google-cloud-bigquery': ["/google-cloud-bigquery"]
'p:google-cloud-bigquery-storage': ["/google-cloud-bigquery-storage"]
'p:google-cloud-pub-sub': ["/google-cloud-pub-sub"]
'p:google-cloud-pub-sub-grpc': ["/google-cloud-pub-sub-grpc"]
'p:google-cloud-storage': ["/google-cloud-storage"]
'p:google-common': ["/google-common"]
'p:google-fcm': ["/google-fcm"]
'p:hbase': ["/hbase"]
'p:hdfs': ["/hdfs"]
'p:huawei-push-kit': ["/huawei-push-kit"]
'p:influxdb': ["/influxdb"]
'p:ironmq': ["/ironmq"]
'p:jms': ["/jms"]
'p:jakarta-jms': ["/jakarta-jms"]
'p:json-streaming': ["/json-streaming"]
'p:kinesis': ["/kinesis"]
'p:mongodb': ["/mongodb"]
'p:mqtt': ["/mqtt"]
'p:mqtt-streaming': ["/mqtt-streaming", "/mqtt-streaming-bench"]
'p:pravega': ["/pravega"]
'p:recordio': ["/simple-codecs"]
'p:reference': ["/reference"]
'p:slick': ["/slick"]
'p:sns': ["/sns"]
'p:solr': ["/solr"]
'p:spring-web': ["/spring-web"]
'p:sqs': ["/sqs"]
'p:sse': ["/sse"]
'p:testkit': ["/testkit"]
'p:text': ["/text"]
'p:udp': ["/udp"]
'p:unix-domain-socket': ["/unix-domain-socket"]
'p:xml': ["/xml"]
