# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes
changelog:
  categories:
    - title: 'AMQP'
      labels: 'p:amqp'
    - title: 'Apache Solr'
      labels: 'p:solr'
    - title: 'Apache HDFS'
      labels: 'p:hdfs'
    - title: 'Apache Kudu'
      labels: 'p:kudu'
    - title: 'AvroParquet'
      labels: 'p:avroparquet'
    - title: 'AWS EventBridge'
      labels: 'p:aws-event-bridge'
    - title: 'AWS Lambda'
      labels: 'p:aws-lambda'
    - title: 'AWS Kinesis'
      labels: 'p:kinesis'
    - title: 'AWS S3'
      labels: 'p:aws-s3'
    - title: 'AWS SNS'
      labels: 'p:aws-sns'
    - title: 'AWS SQS'
      labels: 'p:aws-sqs'
    - title: 'Azure Storage Queue'
      labels: 'p:azure-storage-queue'
    - title: 'Cassandra'
      labels: 'p:cassandra'
    - title: 'Comma-separated Values (CSV)'
      labels: 'p:csv'
    - title: 'Couchbase'
      labels: 'p:couchbase'
    - title: 'Dynamo DB'
      labels: 'p:dynamodb'
    - title: 'Elasticsearch'
      labels: 'p:elasticsearch'
    - title: 'File'
      labels: 'p:file'
    - title: 'FTP'
      labels: 'p:ftp'
    - title: 'Geode'
      labels: 'p:geode'
    - title: 'Google Cloud BigQuery'
      labels: 'p:google-cloud-bigquery'
    - title: 'Google Cloud BigQuery Storage'
      labels: 'p:google-cloud-bigquery-storage'
    - title: 'Google Cloud Pub/Sub'
      labels: 'p:google-cloud-pub-sub'
    - title: 'Google Cloud Pub/Sub gRPC'
      labels: 'p:google-cloud-pub-sub-grpc'
    - title: 'Google Cloud Storage'
      labels: 'p:google-cloud-storage'
    - title: 'Google FCM (Firebase)'
      labels: 'p:google-fcm'
    - title: 'HBase'
      labels: 'p:hbase'
    - title: 'Huawei Push Kit'
      labels: 'p:huawei-push-kit'
    - title: 'InfluxDB'
      labels: 'p:influxdb'
    - title: 'IronMQ'
      labels: 'p:ironmq'
    - title: 'JDBC'
      labels: 'p:jdbc'
    - title: 'JMS'
      labels: 'p:jms'
    - title: 'Json streaming'
      labels: 'p:json-streaming'
    - title: 'MongoDB'
      labels: 'p:mongodb'
    - title: 'MQTT'
      labels: 'p:mqtt'
    - title: 'MQTT Streaming'
      labels: 'p:mqtt-streaming'
    - title: 'Pravega'
      labels: 'p:pravega'
    - title: 'Reference'
      labels: 'p:reference'
    - title: 'Server-sent events (SSE)'
      labels: 'p:sse'
    - title: 'Simple Codecs'
      labels: 'p:recordio'
    - title: 'Slick'
      labels: 'p:slick'
    - title: 'Spring Web'
      labels: 'p:spring-web'
    - title: 'Text'
      labels: 'p:text'
    - title: 'UDP'
      labels: 'p:udp'
    - title: 'Unix Domain Socket'
      labels: 'p:unix-domain-socket'
    - title: 'XML'
      labels: 'p:xml'
    - title: Other Changes
      labels:
          - "*"
