addSbtPlugin("de.heikoseeberger"                 % "sbt-header"       % "1.5.1")
addSbtPlugin("org.scalariform"                   % "sbt-scalariform"  % "1.5.1")
addSbtPlugin("com.jsuereth"                      % "sbt-pgp"          % "1.0.0")
addSbtPlugin("com.dwijnand"                      % "sbt-dynver"       % "1.0.0")
addSbtPlugin("com.lightbend.paradox"             % "sbt-paradox"      % "0.2.5")
addSbtPlugin("com.eed3si9n"                      % "sbt-unidoc"       % "0.3.3")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "0.2.4")
